# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- test -workspace MCUIImageAdvancedExample/UIImageAdvancedExample.xcworkspace -scheme UIImageAdvancedExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
